### ISSUE TITLE
Public headers missing when using Tuist

### ISSUE THREAD

**Issue by azilbershtein** [BranchMetrics/ios-branch-sdk-spm#22]
### Describe the bug

When trying to add Branch as a dependency via Tuist (https://tuist.io/) it doesn't recognize the headers.

In order to fix that can you put all the headers on the same folder (ex. Public) and set the "publicHeadersPath" in the Packag.swift to the right path?
For example if we move "BranchSDK.h" to the BranchSDK folder and set the path to "." everything works.
See some example here
https://github.com/getsentry/sentry-cocoa/tree/main/Sources/Sentry/Public 

### Steps to reproduce

1.Try to add Branch as a dependency via Tuist
2.
3.

### Expected behavior

Headers can be found

### SDK Version

3.0.0

### XCode Version

15.0

### Device

All

### OS

All

**Comment by echo-branch** [comment]
@azilbershtein 
I'm not able to repro the issue as described. Are you using the default static library build or dynamic? There is a known issue the static library build that we have a ticket in backlog for.

Also are you willing to share some of the other libraries you're using in case it's a possible conflict.  Thanks.

**Comment by azilbershtein** [comment]
@echo-branch Thanks for your response.
It has nothing to do with conflicts, have you tried reproduce it via tuist?
Here's an example project of Tuist with only Branch as a dependency, you can try it out.
But the fix is simple, as I wrote, just move the .h file to the main folder and change the headers search to ".", that's it, and everything will work, both Tuist and native SPM.
[tuist_example_301.zip](https://github.com/BranchMetrics/ios-branch-sdk-spm/files/13533582/tuist_example_301.zip)

**Comment by echo-branch** [comment]
@azilbershtein 
Just want to provide a status update on this.

I was able to repro the issue reported. It seems to be related to using tuist with `Dependencies.swift`. When using the Xcode native SPM, the current release worked for me. 

https://tuist.github.io/tuist/main/documentation/projectdescription/targetdependency/external(name:condition:)
https://tuist.github.io/tuist/main/documentation/projectdescription/targetdependency/package(product:type:condition:)

The suggested fix did work for both SPM integration options, however our regression tests failed on other integration methods. This isn't too surprising since we made some compromises for backwards compatibility with old integration methods. Currently looking into what needs to be done to fix other integration methods.

**Comment by obetav** [comment]
@echo-branch When can we expect this fix to be ready? We are having production issues that we believe are due to the SDK being not up to date and we can't drag this any longer.
Appreciate your fast response

**Comment by echo-branch** [comment]
@obetav 
Is it possible to try using the `package` option instead of `external` as a workaround?

I had hoped to have this done this week, but unfortunately I've been out of office due to illness.

**Comment by obetav** [comment]
Hi @echo-branch  Hope you feel better! And Merry Christmas!
No it is not possible to do this. We have many other SDKs and libraries that are all up to date and build successfully
Only the branch SDK is not. 
Please, can we wrap this issue as soon as possible this week?

**Comment by echo-branch** [comment]
@obetav 
The 3.1.0 release should address this issue. This release is for SPM users only and should unblock tuist users who cannot use the `package` option. 

We will work to address compatibility other integration methods and test automation in a follow up release this next sprint.

**Comment by azilbershtein** [comment]
@echo-branch That one works great, thank you!
